### ISSUE TITLE
Backup entire server in one zip

### ISSUE THREAD

**Issue by edcous** [MaxMaeder/DriveBackupV2#6]
How do I backup the entire server in one zip?

**Comment by MaxMaeder** [comment]
Use:
```
  - path: "../minecraftServer"
    format: "'Backup-server-'yyyy-M-d--HH-mm'.zip'"
    create: true
    blacklist:
    - "backups"
```

Replace "minecraftServer" with the name of the folder your Minecraft server JAR is in. Don't include parent folders.

Let me know if this works!
