### ISSUE TITLE
[BUG] sftp issue

### ISSUE THREAD

**Issue by hasechris** [MaxMaeder/DriveBackupV2#90]
Hi,

i updated to your newest version 1.5.4 from 1.3.7. Now im getting the following errors when i trigger a backup.

```
minecraft-designworld    | [14:15:10] [Server thread/INFO]: [DriveBackupV2] Scheduling a backup to run at 05:00 AM every  and Monday
minecraft-designworld    | [14:15:10] [Server thread/INFO]: [DriveBackupV2] Config reloaded!
minecraft-designworld    | [14:15:15] [Server thread/INFO]: [DriveBackupV2] Forcing a backup
minecraft-designworld    | [14:15:15] [Thread-69/INFO]: Generating random seed from SecureRandom.
minecraft-designworld    | [14:15:15] [Thread-69/INFO]: Client identity string: SSH-2.0-SSHJ_0.29.0
minecraft-designworld    | [14:15:15] [Thread-69/INFO]: Server identity string: SSH-2.0-OpenSSH_8.4p1 Debian-5
minecraft-designworld    | [14:15:19] [Thread-69/INFO]: Will request `sftp` subsystem
minecraft-designworld    | [14:15:19] [Thread-69/WARN]: net.schmizz.sshj.sftp.SFTPException: EOF while reading packet
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at net.schmizz.sshj.sftp.PacketReader.readIntoBuffer(PacketReader.java:54)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at net.schmizz.sshj.sftp.PacketReader.getPacketLength(PacketReader.java:59)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at net.schmizz.sshj.sftp.PacketReader.readPacket(PacketReader.java:75)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at net.schmizz.sshj.sftp.SFTPEngine.init(SFTPEngine.java:84)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at net.schmizz.sshj.SSHClient.newSFTPClient(SSHClient.java:722)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at ratismal.drivebackup.uploaders.ftp.SFTPUploader.connect(SFTPUploader.java:124)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at ratismal.drivebackup.uploaders.ftp.SFTPUploader.<init>(SFTPUploader.java:51)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at ratismal.drivebackup.uploaders.ftp.FTPUploader.<init>(FTPUploader.java:67)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at ratismal.drivebackup.UploadThread.run(UploadThread.java:210)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at java.lang.Thread.run(Thread.java:748)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]: Exception in thread "Thread-69" java.lang.NullPointerException
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at ratismal.drivebackup.uploaders.ftp.FTPUploader.isAuthenticated(FTPUploader.java:147)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at ratismal.drivebackup.UploadThread.ensureMethodsAuthenticated(UploadThread.java:304)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at ratismal.drivebackup.UploadThread.run(UploadThread.java:213)
minecraft-designworld    | [14:15:19] [Thread-69/WARN]:         at java.lang.Thread.run(Thread.java:748)
minecraft-designworld    | [14:15:38] [RCON Client /192.168.0.1 #3/INFO]: Thread RCON Client /192.168.0.1 shutting down
```

My config.yml looks like this:
```
#
# DriveBackupV2   -   by Max Maeder (MaxTheGinus)
delay: -1
backup-thread-priority: 1
keep-count: 5
local-keep-count: 2
backups-require-players: false
restart-after-backup: false
scheduled-backups: true
backup-schedule-list:
- days:
  - monday
  time: 05:00
backup-list:
- path: .
  format: '''Backup-world-''yyyy-M-d--HH-mm''.zip'''
  create: true
  blacklist:
  - logs/**
  - plugins/dynmap/**
  - crash-reports/**
  - backups/**
  - serverhub/**
  - serverhub_the_end/**
  - serverhub_nether/**
  - designworld/**
  - designworld_the_end/**
  - designworld_nether/**
  - hase-survival/**
  - hase-survival_the_end/**
  - hase-survival_nether/***
googledrive:
  enabled: false
onedrive:
  enabled: false
ftp:
  enabled: true
  hostname: <redacted>
  port: <redacted>
  sftp: true
  ftps: false
  username: backupminecraft
  sftp-public-key: ../../backup_key_mgtsrv001
  working-dir: /data_hdd/minecraft_designworld_backup
messages:
  send-in-chat: true
  prefix: '&6[&4DriveBackupV2&6] '
  default-color: '&3'
advanced:
  metrics: true
  update-check: true
  suppress-errors: false
  date-language: en
  ftp-file-separator: /
  date-timezone: +02:00
dropbox: {}
webdav: {}
version: 2
local-save-directory: backups
remote-save-directory: backups
```

Greetings
hasechris
